--- 
abstract: Use when you want to disable your controller.
author: 
  - Tomohiro Teranishi <tomohiro.teranishi@gmail.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Controller-AllowDisable
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Runtime: 5.7
  Test::More: 0
  Test::Spelling: 0
version: 0.03
