# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Controller-AllowDisable
version:      0.01
version_from: lib/Catalyst/Controller/AllowDisable.pm
installdirs:  site
requires:
    Catalyst::Runtime:             5.7
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
