abstract: Use when you want to disable your controller.
author: Tomohiro Teranishi <tomohiro.teranishi@gmail.com>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Controller-AllowDisable
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Runtime: 5.7
  Test::More: 0
version: 0.02
